import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

export const dynamic = 'force-dynamic';

import { LanguageProvider } from "@/lib/contexts/LanguageContext";
import { DevModeProvider } from "@/lib/contexts/DevModeContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GRCma Case Study Generator",
  description: "Generated by HMAMOUCH",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
          suppressHydrationWarning
        >
          <DevModeProvider>
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </DevModeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
