'use client';
import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
    en: {
        // Nav
        'login': 'Log In',
        'dashboard': 'Go to Platform',
        'price_option': 'One-Time License',
        // Hero
        'hero_tag': 'Live Telemetry: Active',
        'hero_title_1': 'Trust through',
        'hero_title_2': 'Continuous Verification.',
        'hero_desc': 'View our real-time Compliance Posture, verified via automated evidence collection and zero-trust monitoring.',
        'hero_demo': 'Try Interactive Demo',
        'hero_upgrade': 'Upgrade to Enterprise',
        // Status
        'status_title': 'Global System Status',
        'status_desc': 'Real-time uptime monitoring across all regions.',
        'status_all_ok': 'All Systems Operational',
        // Pricing
        'pricing_title': 'Enterprise-Grade Security. Simple Pricing.',
        'pricing_sub': 'One simple license for full access to the GRC Neural Command Center. No hidden fees.',
        'pricing_card_title': 'Enterprise License',
        'pricing_features_1': 'Unlimited AI Usage',
        'pricing_features_2': 'Full Admin Access',
        'pricing_features_3': 'Multi-User Collaboration',
        'pricing_features_4': 'Export to PDF/CSV',
        'pricing_features_5': 'API Access & Webhooks',
        'purchase_btn': 'Purchase Lifetime Access',
        'secure_payment': 'Secure payment via MockPay™',
        // Dashboard Nav
        'nav_overview': 'Overview',
        'nav_governance': 'Governance',
        'nav_risk': 'Risk',
        'nav_operations': 'Operations',
        'nav_audit': 'Audit',
        'nav_zero_trust': 'Zero Trust',
        'nav_guide': 'Guide',
        'nav_copilot': 'Copilot',
        // Dashboard Content
        'dash_title': 'Executive Dashboard',
        'dash_subtitle': 'Real-time GRC metrics and compliance posture',
        'dash_reset': 'Reset Dashboard',
        'dash_score': 'Compliance Score',
        'dash_controls_pending': 'controls pending',
        'dash_no_controls': 'No controls defined',
        'stat_critical_risks': 'Critical Risks',
        'stat_open_actions': 'Open Actions',
        'stat_incidents': 'Incidents',
        'stat_vendors': 'Active Vendors',
        'stat_changes': 'Pending Changes',
        'widget_risk_dist': 'Risk Distribution',
        'widget_no_risk': 'No risk data available',
        'widget_comp_trend': 'Compliance Trend',
        'widget_comp_velocity': 'Compliance Velocity',
        'widget_comp_proj': 'Projected to reach',
        'widget_comp_proj_end': 'by next quarter based on current velocity.',
        'widget_coverage': 'Control Coverage & Risk Mitigation',
        'widget_analytics': 'GRC Analytics',
        'widget_activity': 'Recent Activity',
        'widget_no_activity': 'No recent activity recorded',

        // --- COMMON UI ---
        'common_search': 'Search or filter...',
        'common_filter_active': 'Active Filter',
        'common_clear_filter': 'Clear All',
        'common_delete_all': 'Delete All',
        'common_confirm_delete': 'Are you sure? This cannot be undone.',
        'common_cancel': 'Cancel',
        'common_submit': 'Submit',
        'common_save': 'Save',
        'common_loading': 'Loading...',
        'common_showing': 'Showing',
        'common_of': 'of',

        // --- RISKS PAGE ---
        'risk_title': 'Risk Dashboard',
        'risk_subtitle': 'Real-time AI risk assessment and monitoring',
        'risk_btn_assess': 'Assess Risk',
        'risk_stat_critical': 'Critical Risks',
        'risk_stat_high': 'High Risks',
        'risk_stat_total': 'Total Risks',
        'risk_stat_avg': 'Avg Risk Score',
        'risk_view_list': 'List View',
        'risk_view_heatmap': 'Heatmap View',
        'risk_table_asset': 'Asset/System',
        'risk_table_score': 'Score',
        'risk_table_cat': 'Category',
        'risk_table_narrative': 'Narrative',
        'risk_table_status': 'Status',
        'risk_table_evidence': 'Evidence',
        'risk_modal_title': 'Assess New Risk',
        'risk_modal_desc': 'Use AI to analyze and score risk scenarios.',

        // --- POLICIES PAGE ---
        'policy_title': 'Policy Management',
        'policy_subtitle': 'Manage and enforce organizational security policies',
        'policy_btn_new': 'New Policy',
        'policy_stat_active': 'Active Policies',
        'policy_stat_draft': 'Draft Policies',
        'policy_stat_total': 'Total Documents',
        'policy_table_title': 'Title',
        'policy_table_ver': 'Version',
        'policy_table_status': 'Status',
        'policy_table_owner': 'Owner',
        'policy_table_review': 'Review Date',
        'policy_modal_title': 'Create New Policy',

        // --- INCIDENTS PAGE ---
        'inc_title': 'Incident Management',
        'inc_subtitle': 'Track and manage security incidents response',
        'inc_btn_report': 'Report Incident',
        'inc_stat_critical': 'Critical Issues',
        'inc_stat_open': 'Open Incidents',
        'inc_stat_investigating': 'Under Investigation',
        'inc_stat_resolved': 'Resolved',
        'inc_view_timeline': 'Forensic Timeline',
        'inc_table_title': 'Title',
        'inc_table_sev': 'Severity',
        'inc_table_status': 'Status',
        'inc_table_assign': 'Assigned To',
        'inc_table_reported': 'Reported',
        'inc_modal_title': 'Report New Incident',

        // Processing
        'proc_step_1': 'Analyzing Case Parameters...',
        'proc_step_2': 'Mapping Logic Flow...',
        'proc_step_3': 'Identifying Drivers and Risks...',
        'proc_step_4': 'Structuring Gap Analysis...',
        'proc_step_5': 'Drafting Executive Summary...',
        'proc_step_6': 'Finalizing GRC Report...',
        'proc_title': 'Generating Case Study',

        // Report
        'rep_send_success': 'Report sent successfully!',
        'rep_send_err': 'Error sending email:',
        'rep_import_signin': 'Please sign in to import data.',
        'rep_import_warn_del': 'WARNING: This will DELETE all existing Controls, Risks, and Vendors and replace them with this scenario. Are you sure?',
        'rep_import_warn_app': 'This will append these findings to your GRC platform. Continue?',
        'rep_import_fail': 'Import failed:',
        'rep_ap_title': 'Action Plan',

        // About
        'about_title': 'About GRCma',
        'about_desc': 'A next-generation Governance, Risk, and Compliance intelligence platform designed to streamline audit workflows and ensure regulatory alignment.',
        'about_role': 'GRC Specialist & Creator',
        'about_feat_1': 'Automated Insights',
        'about_feat_1_desc': 'Leveraging AI to generate compliance reports, gap analyses, and remediation actions instantly.',
        'about_feat_2': 'Security First',
        'about_feat_2_desc': 'Built with enterprise security standards, including RBAC, audit logging, and secure data handling.',
        'about_feat_3': 'Modern UX',
        'about_feat_3_desc': 'A premium, responsive interface designed for clarity, speed, and ease of use across all devices.',
        'about_footer': 'GRCma Platform. All rights reserved.',

        // Methodology
        'meth_title': 'Methodology',
        'meth_intro': 'The GRCma generator is built upon a rigorous analysis of public case studies published by NCC Group, a global leader in cyber security and software escrow.',
        'meth_fw_title': 'The Framework',
        'meth_fw_desc': 'Our AI model has been trained to replicate the structural logic and professional tone of top-tier consulting engagements. Each report follows a proven narrative arc:',
        'meth_li_1': 'Executive Summary',
        'meth_li_1_desc': 'A high-level overview for C-Suite stakeholders.',
        'meth_li_2': 'Drivers & Risks',
        'meth_li_2_desc': 'The "Why" behind the engagement.',
        'meth_li_3': 'Gap Analysis',
        'meth_li_3_desc': 'A clear comparison of Current vs. Target states.',
        'meth_li_4': 'Roadmap',
        'meth_li_4_desc': 'Actionable steps for remediation and improvement.',
        'meth_li_5': 'Business Impact',
        'meth_li_5_desc': 'The tangible value delivered.',
        'meth_why_title': 'Why This Matters',
        'meth_why_desc': 'By adopting this structure, organizations can communicate complex GRC challenges in a language that resonates with board members and executives, facilitating faster decision-making and budget approval.',

        // Platform / Home
        'plat_badge': 'AI-Powered Governance • Real-time Compliance',
        'plat_subtitle': 'Enterprise Governance Orchestration',
        'plat_desc': 'Unify Risk, Compliance, and Audit into a single',
        'plat_desc_highlight': 'AI Neural Command Center',
        'plat_system_op': 'System Operational',
        'plat_loading': 'Loading Neural Interface...',

        // Copilot (Case Input)
        'cp_company_name': 'Company Name',
        'cp_company_ph': 'e.g., SecureFlow Payments',
        'cp_framework': 'Target Framework',
        'cp_framework_ph': 'e.g., SOC 2 Type II, ISO 27001, GDPR',
        'cp_size': 'Company Size',
        'cp_size_sel': 'Select size...',
        'cp_size_sm': 'Start-up (1-50 employees)',
        'cp_size_md': 'Mid-Market (51-500 employees)',
        'cp_size_lg': 'Enterprise (500+ employees)',
        'cp_challenge': 'Key Challenge',
        'cp_challenge_ph': 'e.g., Lack of centralized controls, manual evidence collection...',
        'cp_btn_gen': 'Generate Case Study',
        'cp_btn_gen_loading': 'Generating Report...',

        // Zero Trust
        'zt_badge': 'Zero Trust Architecture',
        'zt_title_pre': 'The Path to',
        'zt_title_highlight': 'Zero Trust',
        'zt_desc': 'Transform security from "trust but verify" to "never trust, always verify". Follow the pillars to reach maturity.',
        'zt_btn_start': 'Start Maturity Assessment',
        'zt_step_id_title': 'Identity',
        'zt_step_id_desc': 'Verify every user, every time.',
        'zt_step_dev_title': 'Devices',
        'zt_step_dev_desc': 'Validate device health and compliance.',
        'zt_step_net_title': 'Network',
        'zt_step_net_desc': 'Segment and control traffic.',
        'zt_step_app_title': 'Applications',
        'zt_step_app_desc': 'Secure workloads and APIs.',
        'zt_step_data_title': 'Data',
        'zt_step_data_desc': 'Encrypt and classify data.',

        // User Guide
        'guide_nav_title': 'Analyst Guide',
        'guide_help_title': 'Need live help?',
        'guide_help_desc': 'Our specialized GRC support team is available 24/7 for Enterprise customers.',
        'guide_btn_contact': 'Contact Support (Developer)',

        // Guide - Welcome
        'guide_welcome_title': 'Welcome to GRCma',
        'guide_welcome_intro': 'You are now operating the Governance, Risk, and Compliance Management Architecture. This platform is designed to replace manual spreadsheets with an intelligent, automated neural interface.',
        'guide_goal_title': 'Quick Start Goal',
        'guide_goal_desc': 'Your primary objective is to reach 100% Audit Readiness. You achieve this by identifying Risks, implementing Controls, and uploading Evidence.',
        'guide_role_analyst': 'For Analysts',
        'guide_role_analyst_desc': 'Focus on the Input Interface. Describe your systems or upload documents, and let the AI generate your initial Risk Register and Policy drafts.',
        'guide_role_manager': 'For Managers',
        'guide_role_manager_desc': 'Monitor the Dashboard. Watch the Compliance Score and Risk Heatmap. Approve policies generated by your analysts.',

        // Guide - Dashboard
        'guide_dash_title': 'Understanding Your Workspace',
        'guide_dash_intro': 'The GRCma dashboard is divided into specific functional zones. Here is how to read them:',
        'guide_dash_score': 'Compliance Score',
        'guide_dash_score_desc': 'This central gauge (0-100%) shows your overall audit readiness. It is calculated based on the percentage of implemented controls that have verified evidence.',
        'guide_dash_map': 'Risk Heatmap',
        'guide_dash_map_desc': 'A visual grid showing your top threats.',
        'guide_dash_map_hi': 'Top Right (High Impact/High Likelihood)',
        'guide_dash_map_hi_desc': ': Critical issues requiring immediate attention.',
        'guide_dash_map_lo': 'Bottom Left (Low Impact/Low Likelihood)',
        'guide_dash_map_lo_desc': ': Low priority items to just monitor.',
        'guide_dash_fw': 'Active Frameworks',
        'guide_dash_fw_desc': 'Shows which standards you are tracking (e.g., SOC2, ISO 27001). Clicking a framework filters the entire dashboard to show only relevant gaps.',

        // Guide - Workflows
        'guide_wf_title': 'Core Workflows',
        'guide_wf_intro': 'How to Perform Key Tasks',
        'guide_wf_1_title': '1. Assessing a New Vendor',
        'guide_wf_1_step1': 'Input Vendor Details',
        'guide_wf_1_step1_desc': 'Go to the "Input" tab. Describe the vendor (e.g., "AWS Hosting") and what data they access.',
        'guide_wf_1_step2': 'AI Analysis',
        'guide_wf_1_step2_desc': 'GRCma will auto-identify risks (e.g., "Data Sovereignty") and suggest required controls (e.g., "DPA Signed").',
        'guide_wf_1_step3': 'Review Report',
        'guide_wf_1_step3_desc': 'Check the generated report. If accurate, save it to the Risk Register.',
        'guide_wf_2_title': '2. Prepare for an Audit (Gap Analysis)',
        'guide_wf_2_step1': 'Select Framework',
        'guide_wf_2_step1_desc': 'Choose the target standard (e.g., SOC2) from the filter menu.',
        'guide_wf_2_step2': 'Review Red Items',
        'guide_wf_2_step2_desc': 'Look for Controls marked "Not Implemented". These are your audit gaps.',
        'guide_wf_2_step3': 'Upload Evidence',
        'guide_wf_2_step3_desc': 'For each gap, implement the fix and upload a screenshot or log file as proof.',

        // Guide - Glossary
        'guide_gloss_title': 'GRC Glossary',
        'guide_gloss_intro': 'Common terms you will encounter in the platform.',
        'guide_term_control': 'Control',
        'guide_def_control': 'A safeguard or countermeasure to avoid, detect, counteract, or minimize security risks.',
        'guide_term_evidence': 'Evidence',
        'guide_def_evidence': 'Documentation (screenshots, logs) that proves a Control is actually working.',
        'guide_term_inh_risk': 'Inherent Risk',
        'guide_def_inh_risk': 'The risk level BEFORE you apply any controls.',
        'guide_term_res_risk': 'Residual Risk',
        'guide_def_res_risk': 'The risk level AFTER you apply controls.',

        // Admin
        'admin_panel': 'Admin Panel',
        'admin_team': 'Team & Access',
        'admin_config': 'System Config',
        'admin_dash': 'Admin Dashboard',
        'admin_analytics': 'Analytics Lab',
        'admin_integrations': 'Integrations (CCM)',
        'account_title': 'Account',
        'account_signout': 'Sign Out',

        // Admin Dashboard
        'admin_dash_title': 'Admin Dashboard',
        'admin_dash_sub': 'Platform overview and system management',
        'admin_quick_actions': 'Quick Actions',
        'admin_recent_activity': 'Recent Activity',
        'admin_system_status': 'System Status',
        'admin_status_db': 'Database',
        'admin_status_auth': 'Auth',
        'admin_status_llm': 'LLM API',
        'admin_status_dev': 'DEV Mode',
        'admin_act_risk': 'New Risk',
        'admin_act_incident': 'New Incident',
        'admin_no_activity': 'No recent activity',

        // Admin Users
        'team_title': 'Team Management',
        'team_sub': 'Control access, assign roles, and manage your organization.',
        'team_add_member': 'Add Member',
        'team_active_principals': 'Active Principals',
        'team_pending_invites': 'Pending Invitations',
        'team_invite_modal_title': 'Invite Member',
        'team_invite_modal_desc': 'Authorize a new Google Account to access the platform.',
        'team_invite_email_label': 'Google Email Address',
        'team_invite_role_label': 'Role Assignment',
        'team_invite_send': 'Send Invite',
        'team_revoke': 'Revoke Access',
        'team_revoke_invite': 'Revoke Invitation',

        // Admin Settings
        'config_title': 'System Configuration',
        'config_sub': 'Manage global platform settings and integrations.',
        'config_email_title': 'Email Integration (SMTP)',
        'config_email_desc': 'Configure how the platform sends invitations and alerts.',
        'config_auto_detect': 'We have auto-detected these settings based on your Admin account. Please verify them and provide the App Password.',
        'config_save': 'Save Configuration',
        'config_test': 'Test Connection',
        'config_smtp_host': 'SMTP Host',
        'config_sender': 'Sender Email (Username)',
        'config_app_pass': 'App Password',

        // Analytics
        'analytics_title': 'Predictive Analytics Lab',
        'analytics_sub': 'Experimental forecasting engine powered by historical trend analysis.',
        'analytics_beta': 'Beta Preview',
        'analytics_no_data_title': 'No Data Available',
        'analytics_no_data_desc': 'Create some risks to generate predictive analytics.',
        'analytics_select_risk': 'Select Risk Target',
        'analytics_search_risk': 'Search risks...',
        'analytics_model_proj': 'Risk Projection Model',
        'analytics_model_proj_desc': 'Projected residual risk based on control effectiveness decay and incident velocity.',
        'analytics_model_impact': 'Framework Impact Analysis',
        'analytics_model_impact_desc': 'Estimated compliance drift for linked security frameworks.',

        // Integrations
        'int_title': 'Integrations Hub',
        'int_sub': 'Connect your infrastructure and tools to automatically collect evidence, monitor controls, and detect risks in real-time.',
        'int_search': 'Search integrations...',
        'int_active': 'Active',
        'int_not_connected': 'Not Connected',
        'int_connect': 'Connect',
        'int_disconnect': 'Disconnect',
        'int_build_title': 'Build Your Own Integration',
        'int_build_desc': 'Need to connect a custom tool? Use our API and Webhooks to ingest data from any source.',
        'int_view_api': 'View API Documentation',

        // User Settings
        'set_title': 'Platform Configuration',
        'set_sub': 'Manage your enterprise subscription and monitor AI usage.',
        'set_monitor_title': 'AI Consumption Monitor',
        'set_token_allowance': 'Monthly Token Allowance',
        'set_used': 'Used',
        'set_limit': 'Limit',
        'set_current_tier': 'Current Tier',
        'set_est_cost': 'Est. Cost Avoidance',
        'set_status': 'Status',
        'set_sub_title': 'Subscription',
        'set_plan': 'Plan',
        'set_renewal': 'Renewal',
        'set_manage_billing': 'Manage Billing',
        'set_vendor_infra': 'Vendor-Managed Infrastructure',
        'set_soc2_compliant': 'This platform operates under a SOC 2 Type II compliant environment.',
    },
    fr: {
        // Nav
        'login': 'Se Connecter',
        'dashboard': 'Accéder à la Plateforme',
        'price_option': 'Licence Unique',
        // Hero
        'hero_tag': 'Télémétrie en Direct : Active',
        'hero_title_1': 'La Confiance par',
        'hero_title_2': 'Vérification Continue.',
        'hero_desc': 'Visualisez notre posture de conformité en temps réel, vérifiée via la collecte automatisée de preuves et la surveillance Zero-Trust.',
        'hero_demo': 'Démo Interactive',
        'hero_upgrade': 'Passer à l\'Entreprise',
        // Status
        'status_title': 'État Global du Système',
        'status_desc': 'Surveillance de la disponibilité en temps réel dans toutes les régions.',
        'status_all_ok': 'Tous les systèmes opérationnels',
        // Pricing
        'pricing_title': 'Sécurité d\'Entreprise. Prix Simple.',
        'pricing_sub': 'Une licence simple pour un accès complet au Centre de Commandement Neural GRC. Aucun frais caché.',
        'pricing_card_title': 'Licence Entreprise',
        'pricing_features_1': 'Utilisation IA Illimitée',
        'pricing_features_2': 'Accès Administrateur Complet',
        'pricing_features_3': 'Collaboration Multi-Utilisateurs',
        'pricing_features_4': 'Export PDF/CSV',
        'pricing_features_5': 'Accès API & Webhooks',
        'purchase_btn': 'Acheter l\'Accès à Vie',
        'secure_payment': 'Paiement sécurisé via MockPay™',
        // Dashboard Nav
        'nav_overview': 'Vue d\'ensemble',
        'nav_governance': 'Gouvernance',
        'nav_risk': 'Risque',
        'nav_operations': 'Opérations',
        'nav_audit': 'Audit',
        'nav_zero_trust': 'Zero Trust',
        'nav_guide': 'Guide',
        'nav_copilot': 'Copilot',
        // Dashboard Content
        'dashboard_title': 'Tableau de Bord',

        // Platform / Home
        'plat_badge': 'Architecture Zero Trust • Prêt pour SOC2',
        'plat_subtitle': 'Orchestration de la Gouvernance d\'Entreprise',
        'plat_desc': 'Unifiez le Risque, la Conformité et l\'Audit dans un seul',
        'plat_desc_highlight': 'Centre de Commandement Neural IA',
        'plat_system_op': 'Système Opérationnel',
        'plat_loading': 'Chargement de l\'Interface Neurale...',

        // Copilot (Case Input)
        'cp_company_name': 'Nom de l\'Entreprise',
        'cp_company_ph': 'ex: SecureFlow Paiements',
        'cp_framework': 'Cadre Cible',
        'cp_framework_ph': 'ex: SOC 2 Type II, ISO 27001, RGPD',
        'cp_size': 'Taille de l\'Entreprise',
        'cp_size_sel': 'Sélectionner la taille...',
        'cp_size_sm': 'Start-up (1-50 employés)',
        'cp_size_md': 'PME (51-500 employés)',
        'cp_size_lg': 'Entreprise (500+ employés)',
        'cp_challenge': 'Défi Principal',
        'cp_challenge_ph': 'ex: Manque de contrôles centralisés, collecte manuelle...',
        'cp_btn_gen': 'Générer l\'Étude de Cas',
        'cp_btn_gen_loading': 'Génération du Rapport...',

        // Zero Trust
        'zt_badge': 'Architecture Zero Trust',
        'zt_title_pre': 'Le Chemin vers',
        'zt_title_highlight': 'le Zero Trust',
        'zt_desc': 'Transformez la sécurité du "faire confiance mais vérifier" au "ne jamais faire confiance, toujours vérifier". Suivez les piliers pour atteindre la maturité.',
        'zt_btn_start': 'Commencer l\'Évaluation de Maturité',
        'zt_step_id_title': 'Identité',
        'zt_step_id_desc': 'Vérifier chaque utilisateur, à chaque fois.',
        'zt_step_dev_title': 'Appareils',
        'zt_step_dev_desc': 'Valider la santé et la conformité des appareils.',
        'zt_step_net_title': 'Réseau',
        'zt_step_net_desc': 'Segmenter et contrôler le trafic.',
        'zt_step_app_title': 'Applications',
        'zt_step_app_desc': 'Sécuriser les charges de travail et les API.',
        'zt_step_data_title': 'Données',
        'zt_step_data_desc': 'Chiffrer et classifier les données.',

        // User Guide
        'guide_nav_title': 'Guide de l\'Analyste',
        'guide_help_title': 'Besoin d\'aide en direct ?',
        'guide_help_desc': 'Notre équipe support GRC spécialisée est disponible 24/7 pour les clients Entreprise.',
        'guide_btn_contact': 'Contacter le Support (Développeur)',

        // Guide - Welcome
        'guide_welcome_title': 'Bienvenue sur GRCma',
        'guide_welcome_intro': 'Vous opérez maintenant l\'Architecture de Gestion de la Gouvernance, du Risque et de la Conformité (GRCma). Cette plateforme est conçue pour remplacer les feuilles de calcul manuelles par une interface neurale automatisée et intelligente.',
        'guide_goal_title': 'Objectif de Démarrage Rapide',
        'guide_goal_desc': 'Votre objectif principal est d\'atteindre une Préparation à l\'Audit de 100%. Vous y parviendrez en identifiant les Risques, en mettant en œuvre des Contrôles et en téléchargeant des Preuves.',
        'guide_role_analyst': 'Pour les Analystes',
        'guide_role_analyst_desc': 'Concentrez-vous sur l\'Interface d\'Entrée. Décrivez vos systèmes ou téléchargez des documents, et laissez l\'IA générer votre Registre des Risques initial et vos ébauches de Politiques.',
        'guide_role_manager': 'Pour les Managers',
        'guide_role_manager_desc': 'Surveillez le Tableau de Bord. Observez le Score de Conformité et la Heatmap des Risques. Approuvez les politiques générées par vos analystes.',

        // Guide - Dashboard
        'guide_dash_title': 'Comprendre Votre Espace de Travail',
        'guide_dash_intro': 'Le tableau de bord GRCma est divisé en zones fonctionnelles spécifiques. Voici comment les lire :',
        'guide_dash_score': 'Score de Conformité',
        'guide_dash_score_desc': 'Cette jauge centrale (0-100%) montre votre préparation globale à l\'audit. Elle est calculée sur la base du pourcentage de contrôles mis en œuvre ayant des preuves vérifiées.',
        'guide_dash_map': 'Heatmap des Risques',
        'guide_dash_map_desc': 'Une grille visuelle montrant vos principales menaces.',
        'guide_dash_map_hi': 'Haut Droite (Impact Élevé/Probabilité Élevée)',
        'guide_dash_map_hi_desc': ': Problèmes critiques nécessitant une attention immédiate.',
        'guide_dash_map_lo': 'Bas Gauche (Faible Impact/Faible Probabilité)',
        'guide_dash_map_lo_desc': ': Éléments de faible priorité à surveiller simplement.',
        'guide_dash_fw': 'Cadres Actifs',
        'guide_dash_fw_desc': 'Affiche les normes que vous suivez (ex: SOC2, ISO 27001). Cliquer sur un cadre filtre tout le tableau de bord pour ne montrer que les écarts pertinents.',

        // Guide - Workflows
        'guide_wf_title': 'Flux de Travail Principaux',
        'guide_wf_intro': 'Comment Exécuter les Tâches Clés',
        'guide_wf_1_title': '1. Évaluer un Nouveau Fournisseur',
        'guide_wf_1_step1': 'Entrer les Détails du Fournisseur',
        'guide_wf_1_step1_desc': 'Allez à l\'onglet "Entrée". Décrivez le fournisseur (ex: "Hébergement AWS") et les données auxquelles il accède.',
        'guide_wf_1_step2': 'Analyse IA',
        'guide_wf_1_step2_desc': 'GRCma identifiera automatiquement les risques (ex: "Souveraineté des Données") et suggérera les contrôles requis.',
        'guide_wf_1_step3': 'Revoir le Rapport',
        'guide_wf_1_step3_desc': 'Vérifiez le rapport généré. S\'il est exact, enregistrez-le dans le Registre des Risques.',
        'guide_wf_2_title': '2. Préparer un Audit (Analyse d\'Écart)',
        'guide_wf_2_step1': 'Sélectionner le Cadre',
        'guide_wf_2_step1_desc': 'Choisissez la norme cible (ex: SOC2) dans le menu de filtre.',
        'guide_wf_2_step2': 'Revoir les Éléments Rouges',
        'guide_wf_2_step2_desc': 'Cherchez les Contrôles marqués "Non Mis en Œuvre". Ce sont vos écarts d\'audit.',
        'guide_wf_2_step3': 'Télécharger des Preuves',
        'guide_wf_2_step3_desc': 'Pour chaque écart, implémentez le correctif et téléchargez une capture d\'écran ou un journal comme preuve.',

        // Guide - Glossary
        'guide_gloss_title': 'Glossaire GRC',
        'guide_gloss_intro': 'Termes communs que vous rencontrerez sur la plateforme.',
        'guide_term_control': 'Contrôle',
        'guide_def_control': 'Une sauvegarde ou contre-mesure pour éviter, détecter ou minimiser les risques de sécurité.',
        'guide_term_evidence': 'Preuve',
        'guide_def_evidence': 'Documentation (captures, journaux) prouvant qu\'un Contrôle fonctionne réellement.',
        'guide_term_inh_risk': 'Risque Inhérent',
        'guide_def_inh_risk': 'Le niveau de risque AVANT d\'appliquer des contrôles.',
        'guide_term_res_risk': 'Risque Résiduel',
        'guide_def_res_risk': 'Le niveau de risque APRÈS avoir appliqué des contrôles.',
        'dash_title': 'Tableau de Bord Exécutif',
        'dash_subtitle': 'Métriques GRC en temps réel et posture de conformité',
        'dash_reset': 'Réinitialiser',
        'dash_score': 'Score de Conformité',
        'dash_controls_pending': 'contrôles en attente',
        'dash_no_controls': 'Aucun contrôle défini',
        'stat_critical_risks': 'Risques Critiques',
        'stat_open_actions': 'Actions Ouvertes',
        'stat_incidents': 'Incidents',
        'stat_vendors': 'Fournisseurs Actifs',
        'stat_changes': 'Changements',
        'widget_risk_dist': 'Distribution des Risques',
        'widget_no_risk': 'Aucune donnée de risque',
        'widget_comp_trend': 'Tendance de Conformité',
        'widget_comp_velocity': 'Vélocité de Conformité',
        'widget_comp_proj': 'Projection à',
        'widget_comp_proj_end': 'd\'ici le prochain trimestre.',
        'widget_coverage': 'Couverture des Contrôles & Atténuation',
        'widget_analytics': 'Analytique GRC',
        'widget_activity': 'Activité Récente',
        'widget_no_activity': 'Aucune activité récente',

        // --- COMMON UI ---
        'common_search': 'Rechercher ou filtrer...',
        'common_filter_active': 'Filtre Actif',
        'common_clear_filter': 'Tout Effacer',
        'common_delete_all': 'Tout Supprimer',
        'common_confirm_delete': 'Êtes-vous sûr ? Cette action est irréversible.',
        'common_cancel': 'Annuler',
        'common_submit': 'Soumettre',
        'common_save': 'Enregistrer',
        'common_loading': 'Chargement...',
        'common_showing': 'Affichage de',
        'common_of': 'sur',

        // --- RISKS PAGE ---
        'risk_title': 'Tableau de Bord des Risques',
        'risk_subtitle': 'Évaluation et surveillance des risques par IA en temps réel',
        'risk_btn_assess': 'Évaluer un Risque',
        'risk_stat_critical': 'Risques Critiques',
        'risk_stat_high': 'Risques Élevés',
        'risk_stat_total': 'Total des Risques',
        'risk_stat_avg': 'Score Moyen',
        'risk_view_list': 'Vue Liste',
        'risk_view_heatmap': 'Vue Thermique',
        'risk_table_asset': 'Actif/Système',
        'risk_table_score': 'Score',
        'risk_table_cat': 'Catégorie',
        'risk_table_narrative': 'Narratif',
        'risk_table_status': 'Statut',
        'risk_table_evidence': 'Preuve',
        'risk_modal_title': 'Évaluer Nouveau Risque',
        'risk_modal_desc': 'Utiliser l\'IA pour analyser et chiffrer les scénarios de risque.',

        // --- POLICIES PAGE ---
        'policy_title': 'Gestion des Politiques',
        'policy_subtitle': 'Gérer et appliquer les politiques de sécurité organisationnelles',
        'policy_btn_new': 'Nouvelle Politique',
        'policy_stat_active': 'Politiques Actives',
        'policy_stat_draft': 'Brouillons',
        'policy_stat_total': 'Documents Totaux',
        'policy_table_title': 'Titre',
        'policy_table_ver': 'Version',
        'policy_table_status': 'Statut',
        'policy_table_owner': 'Propriétaire',
        'policy_table_review': 'Date de Revue',
        'policy_modal_title': 'Créer Nouvelle Politique',

        // --- INCIDENTS PAGE ---
        'inc_title': 'Gestion des Incidents',
        'inc_subtitle': 'Suivi et réponse aux incidents de sécurité',
        'inc_btn_report': 'Signaler un Incident',
        'inc_stat_critical': 'Problèmes Critiques',
        'inc_stat_open': 'Incidents Ouverts',
        'inc_stat_investigating': 'En Investigation',
        'inc_stat_resolved': 'Résolus',
        'inc_view_timeline': 'Chronologie Forensique',
        'inc_table_title': 'Titre',
        'inc_table_sev': 'Sévérité',
        'inc_table_status': 'Statut',
        'inc_table_assign': 'Assigné à',
        'inc_table_reported': 'Signalé le',
        'inc_modal_title': 'Signaler un Incident',

        // Processing
        'proc_step_1': 'Analyse des Paramètres du Cas...',
        'proc_step_2': 'Cartographie du Flux Logique...',
        'proc_step_3': 'Identification des Facteurs et Risques...',
        'proc_step_4': 'Structuration de l\'Analyse d\'Écart...',
        'proc_step_5': 'Rédaction du Résumé Exécutif...',
        'proc_step_6': 'Finalisation du Rapport GRC...',
        'proc_title': 'Génération de l\'Étude de Cas',

        // Report
        'rep_send_success': 'Rapport envoyé avec succès !',
        'rep_send_err': 'Erreur lors de l\'envoi de l\'email :',
        'rep_import_signin': 'Veuillez vous connecter pour importer les données.',
        'rep_import_warn_del': 'ATTENTION : Cela SUPPRIMERA tous les Contrôles, Risques et Fournisseurs existants pour les remplacer par ce scénario. Êtes-vous sûr ?',
        'rep_import_warn_app': 'Cela ajoutera ces conclusions à votre plateforme GRC. Continuer ?',
        'rep_import_fail': 'Import échoué :',
        'rep_ap_title': 'Plan d\'Action',

        // About
        'about_title': 'À propos de GRCma',
        'about_desc': 'Une plateforme d\'intelligence GRC de nouvelle génération conçue pour rationaliser les flux d\'audit et assurer l\'alignement réglementaire.',
        'about_role': 'Spécialiste GRC & Créateur',
        'about_feat_1': 'Insights Automatisés',
        'about_feat_1_desc': 'Exploiter l\'IA pour générer des rapports de conformité, des analyses d\'écart et des actions de remédiation instantanément.',
        'about_feat_2': 'Sécurité en Premier',
        'about_feat_2_desc': 'Construit avec des normes de sécurité d\'entreprise, incluant RBAC, journalisation d\'audit et traitement sécurisé des données.',
        'about_feat_3': 'UX Moderne',
        'about_feat_3_desc': 'Une interface premium et réactive conçue pour la clarté, la vitesse et la facilité d\'utilisation sur tous les appareils.',
        'about_footer': 'Plateforme GRCma. Tous droits réservés.',

        // Methodology
        'meth_title': 'Méthodologie',
        'meth_intro': 'Le générateur GRCma est construit sur une analyse rigoureuse d\'études de cas publiques publiées par NCC Group, un leader mondial en cyber sécurité et séquestre logiciel.',
        'meth_fw_title': 'Le Cadre',
        'meth_fw_desc': 'Notre modèle IA a été entraîné pour répliquer la logique structurelle et le ton professionnel des engagements de conseil de haut niveau. Chaque rapport suit un arc narratif éprouvé :',
        'meth_li_1': 'Résumé Exécutif',
        'meth_li_1_desc': 'Une vue d\'ensemble de haut niveau pour les parties prenantes C-Suite.',
        'meth_li_2': 'Facteurs & Risques',
        'meth_li_2_desc': 'Le "Pourquoi" derrière l\'engagement.',
        'meth_li_3': 'Analyse d\'Écart',
        'meth_li_3_desc': 'Une comparaison claire des états Actuels vs Cibles.',
        'meth_li_4': 'Feuille de Route',
        'meth_li_4_desc': 'Étapes réalisables pour la remédiation et l\'amélioration.',
        'meth_li_5': 'Impact Commercial',
        'meth_li_5_desc': 'La valeur tangible délivrée.',
        'meth_why_title': 'Pourquoi c\'est Important',
        'meth_why_desc': 'En adoptant cette structure, les organisations peuvent communiquer des défis GRC complexes dans un langage qui résonne avec les membres du conseil et les dirigeants, facilitant la prise de décision rapide et l\'approbation budgétaire.',

        // Admin
        'admin_panel': 'Panneau Admin',
        'admin_team': 'Équipe & Accès',
        'admin_config': 'Config Système',
        'admin_dash': 'Tableau de Bord Admin',
        'admin_analytics': 'Labo Analytique',
        'admin_integrations': 'Intégrations (CCM)',
        'account_title': 'Compte',
        'account_signout': 'Se Déconnecter',

        // Admin Dashboard
        'admin_dash_title': 'Tableau de Bord Admin',
        'admin_dash_sub': 'Vue d\'ensemble de la plateforme et gestion système',
        'admin_quick_actions': 'Actions Rapides',
        'admin_recent_activity': 'Activité Récente',
        'admin_system_status': 'État du Système',
        'admin_status_db': 'Base de Données',
        'admin_status_auth': 'Auth',
        'admin_status_llm': 'API LLM',
        'admin_status_dev': 'Mode DEV',
        'admin_act_risk': 'Nouveau Risque',
        'admin_act_incident': 'Nouvel Incident',
        'admin_no_activity': 'Aucune activité récente',

        // Admin Users
        'team_title': 'Gestion d\'Équipe',
        'team_sub': 'Contrôler l\'accès, assigner les rôles et gérer votre organisation.',
        'team_add_member': 'Ajouter Membre',
        'team_active_principals': 'Principaux Actifs',
        'team_pending_invites': 'Invitations en Attente',
        'team_invite_modal_title': 'Inviter Membre',
        'team_invite_modal_desc': 'Autoriser un nouveau Compte Google à accéder à la plateforme.',
        'team_invite_email_label': 'Adresse Email Google',
        'team_invite_role_label': 'Assignation de Rôle',
        'team_invite_send': 'Envoyer Invitation',
        'team_revoke': 'Révoquer Accès',
        'team_revoke_invite': 'Révoquer Invitation',

        // Admin Settings
        'config_title': 'Configuration Système',
        'config_sub': 'Gérer les paramètres globaux et les intégrations.',
        'config_email_title': 'Intégration Email (SMTP)',
        'config_email_desc': 'Configurer l\'envoi d\'invitations et d\'alertes.',
        'config_auto_detect': 'Nous avons auto-détecté ces paramètres basés sur votre compte Admin. Veuillez les vérifier.',
        'config_save': 'Enregistrer Configuration',
        'config_test': 'Tester Connexion',
        'config_smtp_host': 'Hôte SMTP',
        'config_sender': 'Email Expéditeur',
        'config_app_pass': 'Mot de Passe App',

        // Analytics
        'analytics_title': 'Labo Analytique Prédictif',
        'analytics_sub': 'Moteur de prévision expérimental basé sur l\'analyse de tendances historiques.',
        'analytics_beta': 'Aperçu Bêta',
        'analytics_no_data_title': 'Aucune Donnée Disponible',
        'analytics_no_data_desc': 'Créez des risques pour générer des analyses prédictives.',
        'analytics_select_risk': 'Sélectionner Risque Cible',
        'analytics_search_risk': 'Rechercher risques...',
        'analytics_model_proj': 'Modèle de Projection de Risque',
        'analytics_model_proj_desc': 'Risque résiduel projeté basé sur la dégradation de l\'efficacité des contrôles.',
        'analytics_model_impact': 'Analyse d\'Impact Cadre',
        'analytics_model_impact_desc': 'Dérive de conformité estimée pour les cadres de sécurité liés.',

        // Integrations
        'int_title': 'Hub d\'Intégrations',
        'int_sub': 'Connectez votre infrastructure pour collecter automatiquement des preuves et surveiller les risques.',
        'int_search': 'Rechercher intégrations...',
        'int_active': 'Actif',
        'int_not_connected': 'Non Connecté',
        'int_connect': 'Connecter',
        'int_disconnect': 'Déconnecter',
        'int_build_title': 'Construire Votre Intégration',
        'int_build_desc': 'Besoin de connecter un outil personnalisé ? Utilisez notre API.',
        'int_view_api': 'Voir Documentation API',

        // User Settings
        'set_title': 'Configuration Plateforme',
        'set_sub': 'Gérer votre abonnement entreprise et surveiller l\'utilisation IA.',
        'set_monitor_title': 'Moniteur Consommation IA',
        'set_token_allowance': 'Allocation Mensuelle de Tokens',
        'set_used': 'Utilisé',
        'set_limit': 'Limite',
        'set_current_tier': 'Niveau Actuel',
        'set_est_cost': 'Évitement Coût Est.',
        'set_status': 'Statut',
        'set_sub_title': 'Abonnement',
        'set_plan': 'Plan',
        'set_renewal': 'Renouvellement',
        'set_manage_billing': 'Gérer Facturation',
        'set_vendor_infra': 'Infrastructure Gérée par Fournisseur',
        'set_soc2_compliant': 'Cette plateforme opère dans un environnement conforme SOC 2 Type II.',
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations['en']] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
